version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    groups:
      ci-dependencies:
        patterns:
          - "*"
