name: Build and deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: 
          - python: "3.8"
            tag: "3.8-cuda11.8"
          - python: "3.9"
            tag: "3.9-cuda11.8"
          - python: "3.10"
            tag: "3.10-cuda11.8"

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        build-args: PYTHON_VERSION=${{ matrix.version.python }}
        tags: radixai/python-gpu:${{ matrix.version.tag }}