name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8"]
        cuda-version: ["11.8"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        build-args: PYTHON_VERSION=${{ matrix.python-version }},CUDA_VERSION=${{ matrix.cuda-version }}
        context: .
        platforms: linux/amd64,linux/arm64
        tags: radixai/python-gpu:${{ matrix.python-version.tag }}-cuda${{ matrix.cuda-version.tag }}

    - name: Test Docker image
      run: docker run --rm ${{ env.TEST_TAG }}
